<section class="catalog">
    <div class="container">
            <?php echo "Корзина пользователя " .$_SESSION['name'] ?>
        <div class="catalog__flex">
            <div class="catalog__row">
                <?php foreach($products as $product):?>

                    <div class="catalog__col">
                        <div class="catalog__card card">
                            <div class="card__image"><img src="<?php echo $product->getPictures()?>" alt=""/></div>
                            <div class="card__body">
                                <div class="card__title"><?php echo $product->getTitle()?></div>
                                <div class="card__text"><?php echo $product->getDesr()?></div>
                                <div class="card__text">Quantity: <?php echo $product->getQuantity()?></div>
                                <div class="card__bottom">
                                    <div class="card__cost">$<?php echo $product->getPrice()?></div>
                                </div>
                            </div>
                        </div>

                    </div>
                    </form>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</section>

<style>
    @import url("https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;700&display=swap");
    *,
    *::before,
    *::after {
        box-sizing: border-box;
    }
    body {
        margin: 0;
        padding: 0;
        font-family: 'Rubik', sans-serif;
    }
    .container {
        padding: 0 30px;
        max-width: 1200px;
        margin: 0 auto;
    }
    .card {
        border-radius: 15px;
        overflow: hidden;
        height: 100%;
        display: flex;
        flex-direction: column;
        background: #fff;
    }
    .card__image {
        height: 200px;
        overflow: hidden;
        width: 100%;
        border-radius: 15px;
    }
    .card__image img {
        display: block;
        width: 100%;
        height: 100%;
        -o-object-fit: cover;
        object-fit: cover;
    }
    .card__body {
        padding: 15px;
        flex: 1;
        display: flex;
        flex-direction: column;
    }
    .card__title {
        font-size: 24px;
        text-align: center;
        margin-bottom: 15px;
    }
    .card__text {
        text-align: center;
        font-size: 16px;
        flex: 1;
        margin-bottom: 15px;
        font-weight: 300;
    }
    .card__bottom {
        display: flex;
        align-items: center;
        justify-content: space-evenly;
    }
    .card__cost {
        font-size: 24px;
        color: #4a60d7;
        font-weight: 300;
    }
    .button {
        text-align: center;
    }
    .button a {
        display: inline-flex;
        padding: 0 15px;
        background: #4a60d7;
        align-items: center;
        justify-content: center;
        text-align: center;
        height: 40px;
        width: 100px;
        color: #fff;
        border-radius: 5px;
        text-decoration: none;
        transition: all 0.6s ease;
    }
    .button a:hover {
        background: #40ffdc;
    }
    .catalog {
        background: #f1f1f1;
        padding: 60px 0;
    }
    .catalog__title {
        margin-bottom: 60px;
    }
    .catalog__row {
        display: flex;
        flex-wrap: wrap;
        margin: 0 -15px -30px;
    }
    .catalog__col {
        width: 33.33333333%;
        padding: 0 15px 30px;
    }

    /* General button style */
    .btn {
        border: none;
        font-family: 'Lato';
        font-size: inherit;
        color: inherit;
        background: none;
        cursor: pointer;
        padding: 25px 80px;
        display: inline-block;
        margin: 15px 30px;
        text-transform: uppercase;
        letter-spacing: 1px;
        font-weight: 700;
        outline: none;
        position: relative;
        -webkit-transition: all 0.3s;
        -moz-transition: all 0.3s;
        transition: all 0.3s;
    }

    .btn:after {
        content: '';
        position: absolute;
        z-index: -1;
        -webkit-transition: all 0.3s;
        -moz-transition: all 0.3s;
        transition: all 0.3s;
    }

    /* Pseudo elements for icons */
    .btn:before {
        font-family: 'FontAwesome';
        speak: none;
        font-style: normal;
        font-weight: normal;
        font-variant: normal;
        text-transform: none;
        line-height: 1;
        position: relative;
        -webkit-font-smoothing: antialiased;
    }


    /* Icon separator */
    .btn-sep {
        padding: 25px 60px 25px 120px;
    }

    .btn-sep:before {
        background: rgba(0,0,0,0.15);
    }

    /* Button 1 */
    .btn-1 {
        background: #3498db;
        color: #fff;
    }

    .btn-1:hover {
        background: #2980b9;
    }

    .btn-1:active {
        background: #2980b9;
        top: 2px;
    }

    .btn-1:before {
        position: absolute;
        height: 100%;
        left: 0;
        top: 0;
        line-height: 3;
        font-size: 140%;
        width: 60px;
    }

    /* Button 2 */
    .btn-2 {
        background: #2ecc71;
        color: #fff;
    }

    .btn-2:hover {
        background: #27ae60;
    }

    .btn-2:active {
        background: #27ae60;
        top: 2px;
    }

    .btn-2:before {
        position: absolute;
        height: 100%;
        left: 0;
        top: 0;
        line-height: 3;
        font-size: 140%;
        width: 60px;
    }

    /* Button 3 */
    .btn-3 {
        background: #e74c3c;
        color: #fff;
    }

    .btn-3:hover {
        background: #c0392b;
    }

    .btn-3:active {
        background: #c0392b;
        top: 2px;
    }

    .btn-3:before {
        position: absolute;
        height: 100%;
        left: 0;
        top: 0;
        line-height: 3;
        font-size: 140%;
        width: 60px;
    }

    /* Button 3 */
    .btn-4 {
        background: #34495e;
        color: #fff;
    }

    .btn-4:hover {
        background: #2c3e50;
    }

    .btn-4:active {
        background: #2c3e50;
        top: 2px;
    }

    .btn-4:before {
        position: absolute;
        height: 100%;
        left: 0;
        top: 0;
        line-height: 3;
        font-size: 140%;
        width: 60px;
    }

    /* Icons */

    .icon-cart:before {
        content: "\f07a";
    }

    .icon-heart:before {
        content: "\f004";
    }

    .icon-info:before {
        content: "\f05a";
    }

    .icon-send:before {
        content: "\f1d8";
    }

    /* Button 3 */
    .btn-3 {
        background: #e74c3c;
        color: #fff;
    }

    .btn-3:hover {
        background: #c0392b;
    }

    .btn-3:active {
        background: #c0392b;
        top: 2px;
    }

    .btn-3:before {
        position: absolute;
        height: 100%;
        left: 0;
        top: 0;
        line-height: 3;
        font-size: 140%;
        width: 60px;
    }
    @media (max-width: 991.98px) {
        .container {
            padding: 0 15px;
        }
        .popular__col {
            width: 50%;
        }
    }
    @media (max-width: 767.98px) {
        .catalog__col {
            width: 100%;
        }
    }

</style>

