<form action="/order" method="POST">

    <header>
        <h2>Оформление заказа</h2>
    </header>

    <div>
        <label class="desc" id="title1" for="Field1">ФИО</label>
        <div>
            <input id="Field1" name="name" type="text" class="field text fn" value="<?php echo $user->getName() ?>" size="8" tabindex="1">
        </div>
    </div>

    <div>
        <label class="desc" id="title1" for="Field1">Телефон</label>
        <div>
            <input id="Field1" name="phone" type="text" class="field text fn" value="<?php echo $user->getPhone() ?>" size="8" tabindex="1">
        </div>
    </div>

    <div>

        <label class="desc" id="title4" for="Field4">
            Адрес
        </label>

        <div>
            <textarea id="Field4" name="address" spellcheck="true" rows="10" cols="50" tabindex="4"></textarea>
        </div>
    </div>

    <div>
        <label class="desc" id="title4" for="Field4">
            Комментарий
        </label>

        <div>
            <textarea id="Field4" name="comment" spellcheck="true" rows="10" cols="50" tabindex="4"></textarea>
        </div>
    </div>

            <div class="catalog__flex">
                <div class="catalog__row">
                    <?php $sum = 0;?>
                    <?php foreach($userProducts as $userProduct):?>
                        <?php $product = $products[$userProduct->getId()]; ?>
                        <?php $sum += $product->getPrice() * $userProduct->getQuantity(); ?>
                        <div class="catalog__col">
                            <div class="catalog__card card">
                                <div class="card__image"><img src="<?php echo $product->getPictures()?>" alt=""/></div>
                                <div class="card__body">
                                    <div class="card__title"><?php echo $product->getTitle()?></div>
                                    <div class="card__text"><?php echo $product->getDesr()?></div>
                                    <div class="card__text">Количество: <?php echo $userProduct->getQuantity()?></div>
                                    <div class="card__text">Цена: <?php echo $product->getPrice()?> $</div>
                                    <div class="card__bottom">

                                        <div class="card__cost">Сумма
                                            <input type="text" id = "sumPrice" disabled="disabled" name="sumPrice" size="100"
                                                   value="<?php echo $product->getPrice() * $userProduct->getQuantity()?> "
                                                   readonly>$
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    <?php endforeach; ?>

                </div>
            </div>
        <div class="card__cost">Общая сумма
            <input type="text" id = "sumPrice" disabled="disabled" name="sumPrice" size="100"
                   value="<?php echo $sum ?? 0 ?> "
                   readonly>$
        </div>
        <button class="btn btn-2 btn-sep icon-cart" type="submit">Отправить заказ</button>
</form>


<style>
    * {
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
    }

    body {
        padding: 20px 15%;
    }
    form header {
        margin: 0 0 20px 0;
    }
    form header div {
        font-size: 90%;
        color: #999;
    }
    #sumPrice{
        width: 40px;
        font-size: 18px;
    }
    form header h2 {
        margin: 0 0 5px 0;
    }
    form > div {
        clear: both;
        overflow: hidden;
        padding: 1px;
        margin: 0 0 10px 0;
    }
    form > div > fieldset > div > div {
        margin: 0 0 5px 0;
    }
    form > div > label,
    legend {
        width: 25%;
        float: left;
        padding-right: 10px;
    }
    form > div > div,
    form > div > fieldset > div {
        width: 75%;
        float: right;
    }
    form > div > fieldset label {
        font-size: 90%;
    }
    fieldset {
        border: 0;
        padding: 0;
    }

    input[type=text],
    input[type=email],
    input[type=url],
    input[type=password],
    textarea {
        width: 100%;
        border-top: 1px solid #ccc;
        border-left: 1px solid #ccc;
        border-right: 1px solid #eee;
        border-bottom: 1px solid #eee;
    }
    input[type=text],
    input[type=email],
    input[type=url],
    input[type=password] {
        width: 50%;
    }
    input[type=text]:focus,
    input[type=email]:focus,
    input[type=url]:focus,
    input[type=password]:focus,
    textarea:focus {
        outline: 0;
        border-color: #4697e4;
    }

    @media (max-width: 600px) {
        form > div {
            margin: 0 0 15px 0;
        }
        form > div > label,
        legend {
            width: 100%;
            float: none;
            margin: 0 0 5px 0;
        }
        form > div > div,
        form > div > fieldset > div {
            width: 100%;
            float: none;
        }
        input[type=text],
        input[type=email],
        input[type=url],
        input[type=password],
        textarea,
        select {
            width: 100%;
        }
    }
    @media (min-width: 1200px) {
        form > div > label,
        legend {
            text-align: right;
        }
    }

    .card {
        border-radius: 15px;
        overflow: hidden;
        height: 100%;
        display: flex;
        flex-direction: column;
        background: #fff;
    }
    .card__image {
        height: 200px;
        overflow: hidden;
        width: 100%;
        border-radius: 15px;
    }
    .card__image img {
        display: block;
        width: 100%;
        height: 100%;
        -o-object-fit: cover;
        object-fit: cover;
    }
    .card__body {
        padding: 15px;
        flex: 1;
        display: flex;
        flex-direction: column;
    }
    .card__title {
        font-size: 24px;
        text-align: center;
        margin-bottom: 15px;
    }
    .card__text {
        text-align: center;
        font-size: 16px;
        flex: 1;
        margin-bottom: 15px;
        font-weight: 300;
    }
    .card__bottom {
        display: flex;
        align-items: center;
        justify-content: space-evenly;
    }
    .card__cost {
        font-size: 24px;
        color: #4a60d7;
        font-weight: 300;
    }
    .button {
        text-align: center;
    }
    .button a {
        display: inline-flex;
        padding: 0 15px;
        background: #4a60d7;
        align-items: center;
        justify-content: center;
        text-align: center;
        height: 40px;
        width: 100px;
        color: #fff;
        border-radius: 5px;
        text-decoration: none;
        transition: all 0.6s ease;
    }
    .button a:hover {
        background: #40ffdc;
    }
    .catalog {
        background: #f1f1f1;
        padding: 60px 0;
    }
    .catalog__title {
        margin-bottom: 60px;
    }
    .catalog__row {
        display: flex;
        flex-wrap: wrap;
        margin: 0 -15px -30px;
    }
    .catalog__col {
        width: 33.33333333%;
        padding: 0 15px 30px;
    }

    /* General button style */
    .btn {
        border: none;
        font-family: 'Lato';
        font-size: inherit;
        color: inherit;
        background: none;
        cursor: pointer;
        padding: 25px 80px;
        display: inline-block;
        margin: 15px 30px;
        text-transform: uppercase;
        letter-spacing: 1px;
        font-weight: 700;
        outline: none;
        position: relative;
        -webkit-transition: all 0.3s;
        -moz-transition: all 0.3s;
        transition: all 0.3s;
    }

    .btn:after {
        content: '';
        position: absolute;
        z-index: -1;
        -webkit-transition: all 0.3s;
        -moz-transition: all 0.3s;
        transition: all 0.3s;
    }

    /* Pseudo elements for icons */
    .btn:before {
        font-family: 'FontAwesome';
        speak: none;
        font-style: normal;
        font-weight: normal;
        font-variant: normal;
        text-transform: none;
        line-height: 1;
        position: relative;
        -webkit-font-smoothing: antialiased;
    }


    /* Icon separator */
    .btn-sep {
        padding: 25px 60px 25px 120px;
    }

    .btn-sep:before {
        background: rgba(0,0,0,0.15);
    }

    /* Button 1 */
    .btn-1 {
        background: #3498db;
        color: #fff;
    }

    .btn-1:hover {
        background: #2980b9;
    }

    .btn-1:active {
        background: #2980b9;
        top: 2px;
    }

    .btn-1:before {
        position: absolute;
        height: 100%;
        left: 0;
        top: 0;
        line-height: 3;
        font-size: 140%;
        width: 60px;
    }

    /* Button 2 */
    .btn-2 {
        background: #2ecc71;
        color: #fff;
    }

    .btn-2:hover {
        background: #27ae60;
    }

    .btn-2:active {
        background: #27ae60;
        top: 2px;
    }

    .btn-2:before {
        position: absolute;
        height: 100%;
        left: 0;
        top: 0;
        line-height: 3;
        font-size: 140%;
        width: 60px;
    }

    /* Button 3 */
    .btn-3 {
        background: #e74c3c;
        color: #fff;
    }

    .btn-3:hover {
        background: #c0392b;
    }

    .btn-3:active {
        background: #c0392b;
        top: 2px;
    }

    .btn-3:before {
        position: absolute;
        height: 100%;
        left: 0;
        top: 0;
        line-height: 3;
        font-size: 140%;
        width: 60px;
    }

    /* Button 3 */
    .btn-4 {
        background: #34495e;
        color: #fff;
    }

    .btn-4:hover {
        background: #2c3e50;
    }

    .btn-4:active {
        background: #2c3e50;
        top: 2px;
    }

    .btn-4:before {
        position: absolute;
        height: 100%;
        left: 0;
        top: 0;
        line-height: 3;
        font-size: 140%;
        width: 60px;
    }

    /* Icons */

    .icon-cart:before {
        content: "\f07a";
    }

    .icon-heart:before {
        content: "\f004";
    }

    .icon-info:before {
        content: "\f05a";
    }

    .icon-send:before {
        content: "\f1d8";
    }

    /* Button 3 */
    .btn-3 {
        background: #e74c3c;
        color: #fff;
    }

    .btn-3:hover {
        background: #c0392b;
    }

    .btn-3:active {
        background: #c0392b;
        top: 2px;
    }

    .btn-3:before {
        position: absolute;
        height: 100%;
        left: 0;
        top: 0;
        line-height: 3;
        font-size: 140%;
        width: 60px;
    }
    @media (max-width: 991.98px) {
        .container {
            padding: 0 15px;
        }
        .popular__col {
            width: 50%;
        }
    }
    @media (max-width: 767.98px) {
        .catalog__col {
            width: 100%;
        }
    }

</style>